# Generated by Django 5.1.5 on 2025-01-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='mailing_lists',
            field=models.ManyToManyField(related_name='subscribers', to='emails.mailinglist'),
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='mailing_list',
        ),
    ]
