[supervisord]
nodaemon=true

[program:django]
command=gunicorn emaildaemon.wsgi:application --bind 0.0.0.0:8081 --workers 2
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:emaildaemon]
command=python manage.py run_email_daemon
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
